inherit_from: "configs/rgbd/tum/base_config.yaml"

Dataset:
  dataset_path: "../../dataset/cp"
  Calibration:
    fx: 332.232689
    fy: 332.644823
    cx: 333.058485
    cy: 240.998586
    k1: 0.011770
    k2: -0.041851
    p1: 0.000701
    p2: -0.000319
    k3: 0.0
    width: 640
    height: 480
    depth_scale: 4000
    distorted: True
